config-version: 1
#---------------------

#the maximum sequential time an async operation should halt the server
#in milliseconds
async-max-halt-time: 25

#how many ticks to wait till next sync operation
async-tick-delay: 3


